2023-02-26 15:52:44 error: uncaughtException: Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1677423161896, routers=[], readers=[], writers=[]]
Neo4jError: Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1677423161896, routers=[], readers=[], writers=[]]
    at new Neo4jError (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-core\lib\error.js:77:16)
    at newError (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-core\lib\error.js:113:12)
    at RoutingConnectionProvider.<anonymous> (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:633:68)
    at step (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:100:23)
    at Object.next (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:81:53)
    at C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:75:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:71:12)
    at RoutingConnectionProvider._applyRoutingTableIfPossible (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:627:16)
    at RoutingConnectionProvider.<anonymous> (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:450:55)
2023-02-26 15:54:33 error: uncaughtException: Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1677423273015, routers=[], readers=[], writers=[]]
Neo4jError: Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1677423273015, routers=[], readers=[], writers=[]]
    at new Neo4jError (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-core\lib\error.js:77:16)
    at newError (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-core\lib\error.js:113:12)
    at RoutingConnectionProvider.<anonymous> (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:633:68)
    at step (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:100:23)
    at Object.next (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:81:53)
    at C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:75:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:71:12)
    at RoutingConnectionProvider._applyRoutingTableIfPossible (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:627:16)
    at RoutingConnectionProvider.<anonymous> (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:450:55)
2023-02-26 15:55:09 error: uncaughtException: Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1677423308920, routers=[], readers=[], writers=[]]
Neo4jError: Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1677423308920, routers=[], readers=[], writers=[]]
    at new Neo4jError (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-core\lib\error.js:77:16)
    at newError (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-core\lib\error.js:113:12)
    at RoutingConnectionProvider.<anonymous> (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:633:68)
    at step (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:100:23)
    at Object.next (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:81:53)
    at C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:75:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:71:12)
    at RoutingConnectionProvider._applyRoutingTableIfPossible (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:627:16)
    at RoutingConnectionProvider.<anonymous> (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:450:55)
2023-02-26 15:56:57 error: uncaughtException: Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1677423417189, routers=[], readers=[], writers=[]]
Neo4jError: Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1677423417189, routers=[], readers=[], writers=[]]
    at new Neo4jError (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-core\lib\error.js:77:16)
    at newError (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-core\lib\error.js:113:12)
    at RoutingConnectionProvider.<anonymous> (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:633:68)
    at step (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:100:23)
    at Object.next (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:81:53)
    at C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:75:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:71:12)
    at RoutingConnectionProvider._applyRoutingTableIfPossible (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:627:16)
    at RoutingConnectionProvider.<anonymous> (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:450:55)
