2023-03-04 14:53:08 error: uncaughtException: Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1677937987878, routers=[], readers=[], writers=[]]
Neo4jError: Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1677937987878, routers=[], readers=[], writers=[]]
    at new Neo4jError (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-core\lib\error.js:77:16)
    at newError (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-core\lib\error.js:113:12)
    at RoutingConnectionProvider.<anonymous> (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:633:68)
    at step (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:100:23)
    at Object.next (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:81:53)
    at C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:75:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:71:12)
    at RoutingConnectionProvider._applyRoutingTableIfPossible (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:627:16)
    at RoutingConnectionProvider.<anonymous> (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:450:55)
2023-03-04 14:54:30 error: uncaughtException: Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1677938070846, routers=[], readers=[], writers=[]]
Neo4jError: Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1677938070846, routers=[], readers=[], writers=[]]
    at new Neo4jError (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-core\lib\error.js:77:16)
    at newError (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-core\lib\error.js:113:12)
    at RoutingConnectionProvider.<anonymous> (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:633:68)
    at step (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:100:23)
    at Object.next (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:81:53)
    at C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:75:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:71:12)
    at RoutingConnectionProvider._applyRoutingTableIfPossible (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:627:16)
    at RoutingConnectionProvider.<anonymous> (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:450:55)
2023-03-04 14:55:10 error: uncaughtException: Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1677938110392, routers=[], readers=[], writers=[]]
Neo4jError: Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1677938110392, routers=[], readers=[], writers=[]]
    at new Neo4jError (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-core\lib\error.js:77:16)
    at newError (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-core\lib\error.js:113:12)
    at RoutingConnectionProvider.<anonymous> (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:633:68)
    at step (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:100:23)
    at Object.next (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:81:53)
    at C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:75:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:71:12)
    at RoutingConnectionProvider._applyRoutingTableIfPossible (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:627:16)
    at RoutingConnectionProvider.<anonymous> (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:450:55)
2023-03-04 14:56:23 error: uncaughtException: Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1677938183451, routers=[], readers=[], writers=[]]
Neo4jError: Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1677938183451, routers=[], readers=[], writers=[]]
    at new Neo4jError (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-core\lib\error.js:77:16)
    at newError (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-core\lib\error.js:113:12)
    at RoutingConnectionProvider.<anonymous> (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:633:68)
    at step (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:100:23)
    at Object.next (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:81:53)
    at C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:75:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:71:12)
    at RoutingConnectionProvider._applyRoutingTableIfPossible (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:627:16)
    at RoutingConnectionProvider.<anonymous> (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:450:55)
2023-03-04 14:57:47 error: uncaughtException: Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1677938267281, routers=[], readers=[], writers=[]]
Neo4jError: Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1677938267281, routers=[], readers=[], writers=[]]
    at new Neo4jError (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-core\lib\error.js:77:16)
    at newError (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-core\lib\error.js:113:12)
    at RoutingConnectionProvider.<anonymous> (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:633:68)
    at step (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:100:23)
    at Object.next (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:81:53)
    at C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:75:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:71:12)
    at RoutingConnectionProvider._applyRoutingTableIfPossible (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:627:16)
    at RoutingConnectionProvider.<anonymous> (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:450:55)
2023-03-04 14:59:14 error: uncaughtException: Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1677938354427, routers=[], readers=[], writers=[]]
Neo4jError: Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1677938354427, routers=[], readers=[], writers=[]]
    at new Neo4jError (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-core\lib\error.js:77:16)
    at newError (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-core\lib\error.js:113:12)
    at RoutingConnectionProvider.<anonymous> (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:633:68)
    at step (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:100:23)
    at Object.next (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:81:53)
    at C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:75:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:71:12)
    at RoutingConnectionProvider._applyRoutingTableIfPossible (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:627:16)
    at RoutingConnectionProvider.<anonymous> (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:450:55)
2023-03-04 15:00:14 error: uncaughtException: Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1677938414441, routers=[], readers=[], writers=[]]
Neo4jError: Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1677938414441, routers=[], readers=[], writers=[]]
    at new Neo4jError (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-core\lib\error.js:77:16)
    at newError (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-core\lib\error.js:113:12)
    at RoutingConnectionProvider.<anonymous> (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:633:68)
    at step (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:100:23)
    at Object.next (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:81:53)
    at C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:75:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:71:12)
    at RoutingConnectionProvider._applyRoutingTableIfPossible (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:627:16)
    at RoutingConnectionProvider.<anonymous> (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:450:55)
2023-03-04 15:00:49 error: uncaughtException: Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1677938449377, routers=[], readers=[], writers=[]]
Neo4jError: Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1677938449377, routers=[], readers=[], writers=[]]
    at new Neo4jError (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-core\lib\error.js:77:16)
    at newError (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-core\lib\error.js:113:12)
    at RoutingConnectionProvider.<anonymous> (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:633:68)
    at step (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:100:23)
    at Object.next (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:81:53)
    at C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:75:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:71:12)
    at RoutingConnectionProvider._applyRoutingTableIfPossible (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:627:16)
    at RoutingConnectionProvider.<anonymous> (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:450:55)
2023-03-04 15:01:31 error: uncaughtException: Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1677938490951, routers=[], readers=[], writers=[]]
Neo4jError: Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1677938490951, routers=[], readers=[], writers=[]]
    at new Neo4jError (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-core\lib\error.js:77:16)
    at newError (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-core\lib\error.js:113:12)
    at RoutingConnectionProvider.<anonymous> (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:633:68)
    at step (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:100:23)
    at Object.next (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:81:53)
    at C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:75:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:71:12)
    at RoutingConnectionProvider._applyRoutingTableIfPossible (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:627:16)
    at RoutingConnectionProvider.<anonymous> (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:450:55)
2023-03-04 15:01:58 error: uncaughtException: Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1677938518528, routers=[], readers=[], writers=[]]
Neo4jError: Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1677938518528, routers=[], readers=[], writers=[]]
    at new Neo4jError (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-core\lib\error.js:77:16)
    at newError (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-core\lib\error.js:113:12)
    at RoutingConnectionProvider.<anonymous> (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:633:68)
    at step (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:100:23)
    at Object.next (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:81:53)
    at C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:75:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:71:12)
    at RoutingConnectionProvider._applyRoutingTableIfPossible (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:627:16)
    at RoutingConnectionProvider.<anonymous> (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:450:55)
2023-03-04 15:02:19 error: uncaughtException: Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1677938539251, routers=[], readers=[], writers=[]]
Neo4jError: Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1677938539251, routers=[], readers=[], writers=[]]
    at new Neo4jError (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-core\lib\error.js:77:16)
    at newError (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-core\lib\error.js:113:12)
    at RoutingConnectionProvider.<anonymous> (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:633:68)
    at step (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:100:23)
    at Object.next (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:81:53)
    at C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:75:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:71:12)
    at RoutingConnectionProvider._applyRoutingTableIfPossible (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:627:16)
    at RoutingConnectionProvider.<anonymous> (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:450:55)
2023-03-04 15:02:42 error: uncaughtException: Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1677938562613, routers=[], readers=[], writers=[]]
Neo4jError: Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1677938562613, routers=[], readers=[], writers=[]]
    at new Neo4jError (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-core\lib\error.js:77:16)
    at newError (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-core\lib\error.js:113:12)
    at RoutingConnectionProvider.<anonymous> (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:633:68)
    at step (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:100:23)
    at Object.next (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:81:53)
    at C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:75:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:71:12)
    at RoutingConnectionProvider._applyRoutingTableIfPossible (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:627:16)
    at RoutingConnectionProvider.<anonymous> (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:450:55)
2023-03-04 17:13:49 error: uncaughtException: Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1677946429434, routers=[], readers=[], writers=[]]
Neo4jError: Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1677946429434, routers=[], readers=[], writers=[]]
    at new Neo4jError (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-core\lib\error.js:77:16)
    at newError (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-core\lib\error.js:113:12)
    at RoutingConnectionProvider.<anonymous> (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:633:68)
    at step (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:100:23)
    at Object.next (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:81:53)
    at C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:75:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:71:12)
    at RoutingConnectionProvider._applyRoutingTableIfPossible (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:627:16)
    at RoutingConnectionProvider.<anonymous> (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:450:55)
2023-03-04 17:14:51 error: uncaughtException: Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1677946491736, routers=[], readers=[], writers=[]]
Neo4jError: Could not perform discovery. No routing servers available. Known routing table: RoutingTable[database=default database, expirationTime=0, currentTime=1677946491736, routers=[], readers=[], writers=[]]
    at new Neo4jError (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-core\lib\error.js:77:16)
    at newError (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-core\lib\error.js:113:12)
    at RoutingConnectionProvider.<anonymous> (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:633:68)
    at step (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:100:23)
    at Object.next (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:81:53)
    at C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:75:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:71:12)
    at RoutingConnectionProvider._applyRoutingTableIfPossible (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:627:16)
    at RoutingConnectionProvider.<anonymous> (C:\Users\diguo\Documents\feetflight\default\node_modules\neo4j-driver-bolt-connection\lib\connection-provider\connection-provider-routing.js:450:55)
